#!/usr/bin/env python3

def FixColor(value):
	if value == 13:
		value = 14
	if value == 15:
		value = 10
	return value

def Fix(value):
	color1 = int((value & 0xf0) / 16)
	color2 = int(value & 0x0f)
	value = (FixColor(color1) * 16) | FixColor(color2)
	return value
	
with open("victory.vef", "rb") as FILE:

	# Throw away the header
	bytedata = FILE.read(18)

	# Everything else is pixel data
	for i in range(0, 200):

		# Only process rows 16 through 181
		if i < 16 or i > 181:
			bytedata = FILE.read(160)
			continue

		# Print values for every byte in this row
		for j in range(160):
			bytedata = bytearray(FILE.read(1))
			value = bytedata[0]
			print(Fix(value))
